// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxC93O6rjoi3rJfWisyfcgB6Er5QJwY4',
    appId: '1:1043624647826:web:486148c007015ca7a85a4b',
    messagingSenderId: '1043624647826',
    projectId: 'e-commerce-b0ca4',
    authDomain: 'e-commerce-b0ca4.firebaseapp.com',
    storageBucket: 'e-commerce-b0ca4.firebasestorage.app',
    measurementId: 'G-MVZWRL43R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzE_vgnguJ0vBZIXiSZjZcnQyxEWXmriM',
    appId: '1:1043624647826:android:1e64d3c6eabc78a8a85a4b',
    messagingSenderId: '1043624647826',
    projectId: 'e-commerce-b0ca4',
    storageBucket: 'e-commerce-b0ca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKNowN2jjM6NzLPBumDDCubMiu6ZHnjk',
    appId: '1:1043624647826:ios:1bde5a4e988a449ea85a4b',
    messagingSenderId: '1043624647826',
    projectId: 'e-commerce-b0ca4',
    storageBucket: 'e-commerce-b0ca4.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKNowN2jjM6NzLPBumDDCubMiu6ZHnjk',
    appId: '1:1043624647826:ios:1bde5a4e988a449ea85a4b',
    messagingSenderId: '1043624647826',
    projectId: 'e-commerce-b0ca4',
    storageBucket: 'e-commerce-b0ca4.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxC93O6rjoi3rJfWisyfcgB6Er5QJwY4',
    appId: '1:1043624647826:web:4395e97ad7c1e06ca85a4b',
    messagingSenderId: '1043624647826',
    projectId: 'e-commerce-b0ca4',
    authDomain: 'e-commerce-b0ca4.firebaseapp.com',
    storageBucket: 'e-commerce-b0ca4.firebasestorage.app',
    measurementId: 'G-570YHYDGYC',
  );
}
